### ISSUE TITLE
Redesign comparison method

### ISSUE THREAD

**Issue by mhtb32** [bambil/iot-platforms-review#1]
We should define a better way of data representation in this repo. For example, some data can be formed in a table, some in a paragraph, etc.

Also we should make use of many relevant external links to verify our work. Remind me to express my ideas more in person with you.

**Comment by 1995parham** [comment]
Ok, I will remind you about that. But about data presentation, do you have any specific idea? for example by seeing our Kaa information?

**Comment by mhtb32** [comment]
Yes, exactly I have issues on Kaa information. I will talk to you tommorrow
